title: Conference Deadlines
description: Countdowns to top conference deadlines
# author: Abhishek Das

domain: "sajadmanesh.com"
url: "//sajadmanesh.com" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/deadlines"

twitter_hashtag: machinelearning
github_username: sisaman
github_repo: deadlines

markdown: kramdown
ga_id:

include: ['_pages']
